#!/usr/bin/env bash

set -eu -o pipefail

# Only use colors in interactive shells, not from crontab #{{{
# shellcheck disable=SC2034
if [ -t 1 ]; then
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    MAGENTA=$(tput setaf 5)
    CYAN=$(tput setaf 6)
    BOLD=$(tput bold)
    RESET=$(tput sgr0)
else
    RED=
    GREEN=
    MAGENTA=
    CYAN=
    BOLD=
    RESET=
fi #}}}

die() { #{{{
    echo "${RED}ERROR: ${1}${RESET}" >&2
    exit 1
} #}}}

success() { #{{{
    echo "${GREEN}SUCCESS: ${1}${RESET}"
} #}}}

warn() { #{{{
    echo "${MAGENTA}WARNING: ${1}${RESET}" >&2
} #}}}

usage() { #{{{
    cat <<EOF
${CYAN}
Usage: [DEBUG=1] ,bump-version-tag <SCRIPT_name> <VERSION_env>

This script will bump <VERSION_env> in <SCRIPT_name> by reading conventional commit messages from
'git log'. If successful, it will then bump the 'git tag' version to match.
${RESET}
EOF
} #}}}

bump_script_version() { #{{{
    local src_file=$1 version_str=$2 new_version_number=$3
    grep -qE "^\s*(export\s+)?${version_str}" "${src_file}" || die "Version string not found"
    # sed -i.bak 's/old/new/' file && rm file.bak ## works with both macOS and linux
    sed -i.bak -Ee "s/(^.*${version_str}=).*$/\1${new_version_number}/" "${src_file}" && rm "${src_file}.bak"
} #}}}

bump() { #{{{
    local awk_prog
    local level=$1
    local current_version=$2
    if [ "${level}" == 'patch' ]; then
        # shellcheck disable=SC2016
        awk_prog='{OFS="."; $NF+=1; print $0}'
    elif [ "${level}" == 'minor' ]; then
        # shellcheck disable=SC2016
        awk_prog='{OFS="."; $2+=1; $3=0; print $0}'
    elif [ "${level}" == 'major' ]; then
        # shellcheck disable=SC2016
        awk_prog='{OFS="."; $1+=1; $2=0; $3=0; print $0}'
    else
        return 1
    fi
    local result
    result=$(echo "$current_version" | awk -F. "$awk_prog")
    echo "${result:-0.0.0}"
} #}}}

get_version_number() { #{{{
    local src_file version_str current_tag_version current_version result
    src_file=$1 version_str=$2
    current_tag_version=$(git tag --sort=-version:refname --list "v[0-9]*.[0-9]*.[0-9]*" | head -n 1 | tr -d 'v')
    current_version=$(grep -E "^\s*(export\s+)?${version_str}" "${src_file}" | sed -e "s/^.*${version_str}=//" | tr -d '"' | tr -d "'")

    [ -n "${DEBUG:-}" ] && echo "current tag version::${current_tag_version}"
    [ -n "${DEBUG:-}" ] && echo "current script version::${current_version}"
    result="$(printf '%s\n' "$current_tag_version" "$current_version" | sort -V | tail -1)"
    echo "${result:-0.0.0}"
} #}}}

check_in_git_dir() { #{{{
    if ! git rev-parse --git-dir &>/dev/null; then
        die "Not inside a git repository"
    else
        REPO_ROOT="$(git rev-parse --show-toplevel)"
    fi
} #}}}

if [[ "$#" -lt 2 ]]; then
    usage
    exit 1
fi

check_in_git_dir
cd "${REPO_ROOT}" || die "Could not cd to REPO_ROOT"
version_number=$(get_version_number "$1" "$2")

[ -n "${DEBUG:-}" ] && version_number=0.19.0
[ -n "${DEBUG:-}" ] && echo "old:${version_number}"

git_log=$(git log "v${version_number}..HEAD")

if echo "$git_log" | grep -qE '^\s+(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?!: .+|^\s+BREAKING CHANGE: .+'; then
    new_version_number=$(bump major "${version_number}")
elif echo "$git_log" | grep -qE '^\s+feat: .+'; then
    new_version_number=$(bump minor "${version_number}")
else
    new_version_number=$(bump patch "${version_number}")
fi
[ -n "${DEBUG:-}" ] && echo "new:$new_version_number"

bump_script_version "$1" "$2" "${new_version_number}" || die "Script version bump failed"
success "Bumped script version to ${new_version_number}"
(git add "$1" && git commit --amend --reuse-message=HEAD) || die "git commit --amend failed"
warn "History rewritten by 'git commit --amend'"
git tag "v${new_version_number}" || die "git tag failed"
success "Tagged v${new_version_number}"

# vim: set tw=100 expandtab tabstop=2 shiftwidth=2 fdm=marker commentstring=#%s:
