#!/usr/bin/env bash

for repo in $(vcsh list); do
    echo ""
    echo "##### ${repo}":
    vcsh run "${repo}" git log --pretty=format: --name-only | sort -u | sed '/^$/d' >"$HOME/tmp/vcsh-${repo}-all-files.txt"
    vcsh run "${repo}" git ls-tree -r master --name-only >"$HOME/tmp/vcsh-${repo}-files.txt"
    diff "$HOME/tmp/vcsh-${repo}-all-files.txt" "$HOME/tmp/vcsh-${repo}-files.txt"
done
