#!/bin/bash

[ `which cli53` ] || sudo pip install cli53
#[ -d $HOME/tmp ] || mkdir -p $HOME/tmp

FILE="$HOME/Dropbox/lastip"
LASTIP=`cat $FILE`
WAN=`dig +short myip.opendns.com @resolver1.opendns.com`

if [[ "$LASTIP" != "$WAN" ]]; then
	echo "IP changed from $LASTIP to $WAN"
	echo $WAN > $FILE
	cli53 rrcreate --replace --ttl 300 t0m.us @ A $WAN
fi
