#!/bin/bash
[[ "`uname`" = "Darwin" ]] || exit

brew update
brew doctor
brew upgrade

brew install exiftool fdupes gawk getmail gnupg keychain midnight-commander rbenv ruby-build s3cmd wget

# build Avidemux-2.5.6 stable
#   http://www.avidemux.org/smf/index.php?topic=9960.msg53651#msg53651
brew install pkg-config
brew install cmake
brew install aften
brew -v install qt

cd /usr/local/Library/Formula && wget -N https://raw.github.com/2bits/homebrew/newAdm/Library/Formula/avidemux.rb
#brew rm -f avidemux
brew -v install --use-llvm avidemux

# To build or upgrade the lasted unstable revision past 2.5.6
#brew rm -f avidemux
#brew install --use-llvm --HEAD avidemux

# Info On Building 2.6
cd /usr/local/Library/Formula && wget -N https://raw.github.com/2bits/homebrew/newAdm3/Library/Formula/avidemux3.rb
#brew rm -f avidemux3
brew -v install -d --use-llvm avidemux3

brew linkapps

brew list
# 120730 ariel:  a52dec aften avidemux avidemux3 cmake exiftool faac faad2 fdupes fribidi gawk getmail gettext glib gnupg keychain lame libdca libffi libogg libvorbis libvpx mad midnight-commander oniguruma opencore-amr pcre pkg-config qt rbenv readline ruby-build s-lang s3cmd sqlite two-lame wget x264 xvid xz yasm

