#!/bin/bash
[[ "`hostname`" = "manuel" ]] || exit

set -e

BACKUPDIR="${HOME}/backups/getmail"

[ -f "/tmp/getmail.lock" ] && echo "" && echo "WARNING: Lock file exists..." && echo "" && exit
touch /tmp/getmail.lock

cd ${HOME}/.getmail
rcfiles=""
for file in rc-* ; do
  MAILDIRPATH=`echo ${file} | sed -e 's/rc-//' -e 's|:|/|' `
  mkdir -p $BACKUPDIR/$MAILDIRPATH/{cur,new,tmp}
  rcfiles="$rcfiles --rcfile $file"
done

#exec /usr/local/bin/getmail $rcfiles $@
/usr/local/bin/getmail $rcfiles $@
rm /tmp/getmail.lock
