#!/bin/bash
osascript <<END
tell application "iTerm"
 tell the first terminal
  launch session "Default Session"
  tell the last session
   write text "ssh -L 4200:localhost:4243 tom@bethel"
  end tell
 end tell
end tell
END

open /Applications/CrashPlan.app
