#!/usr/bin/env bash

MYHOST=$(uname -n | sed 's/\..*//') # alternative to $(hostname -s), as arch does not install 'hostname' by default

[[ "$(uname)" = "Darwin" ]] || exit

cd "${HOME}/Library/LaunchAgents" || exit
ln -s ../../bin/LaunchAgents/*.plist . 2>/dev/null
for f in us.t0m.*.plist; do
    echo "$f"
    sudo launchctl bootstrap user/"$(id -u)/${HOME}/Library/LaunchAgents/$f"
done

cd /Library/LaunchDaemons || exit
sudo cp /Users/tom/bin/LaunchDaemons-System/us.t0m.*.plist .

if [ "$MYHOST" = "bethel" ]; then
    for f in "${HOME}"/bin/LaunchDaemons-System/*.bethel; do
        F=$(basename "${f//.bethel/}")
        sudo cp "$f" "$F"
    done
fi

for f in us.t0m.*.plist; do
    echo "$f"
    sudo launchctl bootout system /Library/LaunchDaemons/"$f"
    sudo launchctl bootstrap system /Library/LaunchDaemons/"$f"
done

sudo launchctl list | grep us.t0m
