#!/bin/bash
[[ "$(uname)" = "Darwin" ]] || exit

cd "${HOME}/Library/LaunchAgents" && ln -sf ../../bin/LaunchAgents/us.t0m.*.plist .

cd "${HOME}/bin/LaunchDaemons-System" && sudo chown root:wheel us.t0m.*.plist .
cd /Library/LaunchDaemons && sudo ln -sf /Users/tom/bin/LaunchDaemons-System/us.t0m.*.plist .
